/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos;

import java.text.NumberFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;

/**
 *
 * @author user
 */
public class frl_pos extends javax.swing.JFrame {

    DefaultListModel descricao=new DefaultListModel();
    DefaultListModel quantidade=new DefaultListModel();
    DefaultListModel preco=new DefaultListModel();
    DefaultListModel total=new DefaultListModel();
    
    float total_pedido=0;
    
    NumberFormat Moeda=NumberFormat.getCurrencyInstance();
    
    public frl_pos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_cafe = new javax.swing.JLabel();
        bt_capucino = new javax.swing.JLabel();
        bt_carioca = new javax.swing.JLabel();
        bt_galao = new javax.swing.JLabel();
        bt_garoto = new javax.swing.JLabel();
        bt_descafeinado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_mista = new javax.swing.JLabel();
        bt_bolo = new javax.swing.JLabel();
        bt_pizza = new javax.swing.JLabel();
        bt_folhado = new javax.swing.JLabel();
        bt_sandes = new javax.swing.JLabel();
        bt_salgado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bt_agua = new javax.swing.JLabel();
        bt_cola = new javax.swing.JLabel();
        bt_sumo = new javax.swing.JLabel();
        bt_vinho = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bt_adicionar = new javax.swing.JButton();
        bt_remover_item = new javax.swing.JButton();
        bt_quantidade = new javax.swing.JButton();
        bt_remover = new javax.swing.JButton();
        bt_pagamento = new javax.swing.JButton();
        bt_imprimir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_descricao = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_quantidade = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_preco = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_total = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bt_novo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_troco = new javax.swing.JLabel();
        lbl_pedido = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_numerario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cafetaria"));

        bt_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cafe.gif"))); // NOI18N
        bt_cafe.setText("Café");
        bt_cafe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_cafe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_cafeMouseReleased(evt);
            }
        });

        bt_capucino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_capucino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/capucino.gif"))); // NOI18N
        bt_capucino.setText("Capuccino");
        bt_capucino.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_capucino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_capucino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_capucino.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_capucino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_capucinoMouseReleased(evt);
            }
        });

        bt_carioca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_carioca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carioca.gif"))); // NOI18N
        bt_carioca.setText("Carioca");
        bt_carioca.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_carioca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_carioca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_carioca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_carioca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_cariocaMouseReleased(evt);
            }
        });

        bt_galao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_galao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/galao.gif"))); // NOI18N
        bt_galao.setText("Galão");
        bt_galao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_galao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_galao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_galao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_galao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_galaoMouseReleased(evt);
            }
        });

        bt_garoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_garoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/garoto.gif"))); // NOI18N
        bt_garoto.setText("Garoto");
        bt_garoto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_garoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_garoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_garoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_garoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_garotoMouseReleased(evt);
            }
        });

        bt_descafeinado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_descafeinado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/descafeinado.gif"))); // NOI18N
        bt_descafeinado.setText("Descafeinado");
        bt_descafeinado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_descafeinado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_descafeinado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_descafeinado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_descafeinado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_descafeinadoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_capucino, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_carioca, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_galao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_garoto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(bt_descafeinado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bt_carioca, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_descafeinado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_capucino, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_garoto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_galao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pastelaria"));

        bt_mista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_mista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mista.gif"))); // NOI18N
        bt_mista.setText("Mista");
        bt_mista.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_mista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_mista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_mista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_mista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_mistaMouseReleased(evt);
            }
        });

        bt_bolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_bolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_bolo.setText("Bolo");
        bt_bolo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_bolo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_bolo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_bolo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_bolo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_boloMouseReleased(evt);
            }
        });

        bt_pizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_pizza.setText("Pizza");
        bt_pizza.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_pizza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_pizza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_pizza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_pizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_pizzaMouseReleased(evt);
            }
        });

        bt_folhado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_folhado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_folhado.setText("Folhado");
        bt_folhado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_folhado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_folhado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_folhado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_folhado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_folhadoMouseReleased(evt);
            }
        });

        bt_sandes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_sandes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mista.gif"))); // NOI18N
        bt_sandes.setText("Sandes");
        bt_sandes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_sandes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_sandes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sandes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_sandes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_sandesMouseReleased(evt);
            }
        });

        bt_salgado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_salgado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salgado.gif"))); // NOI18N
        bt_salgado.setText("Salgado");
        bt_salgado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_salgado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_salgado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_salgado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_salgado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_salgadoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_mista, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_salgado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_bolo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_folhado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sandes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_mista, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_salgado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_bolo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_sandes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_folhado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bebidas"));

        bt_agua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_agua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agua.gif"))); // NOI18N
        bt_agua.setText("Água");
        bt_agua.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_agua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_agua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_agua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_agua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_aguaMouseReleased(evt);
            }
        });

        bt_cola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cola.gif"))); // NOI18N
        bt_cola.setText("Cola");
        bt_cola.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_cola.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_colaMouseReleased(evt);
            }
        });

        bt_sumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_sumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sumo.gif"))); // NOI18N
        bt_sumo.setText("Sumo");
        bt_sumo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_sumo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_sumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_sumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_sumoMouseReleased(evt);
            }
        });

        bt_vinho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_vinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vinho.gif"))); // NOI18N
        bt_vinho.setText("Vinho");
        bt_vinho.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_vinho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_vinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_vinho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_vinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_vinhoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cola, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sumo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_sumo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_cola, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_adicionar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_adicionar.setForeground(new java.awt.Color(0, 153, 0));
        bt_adicionar.setText("Adicionar Item");
        bt_adicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bt_remover_item.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_remover_item.setForeground(new java.awt.Color(0, 153, 0));
        bt_remover_item.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_remover_item.setLabel("Remover Item");
        bt_remover_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_remover_itemActionPerformed(evt);
            }
        });

        bt_quantidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_quantidade.setForeground(new java.awt.Color(0, 153, 0));
        bt_quantidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_quantidade.setLabel("Quantidade");
        bt_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quantidadeActionPerformed(evt);
            }
        });

        bt_remover.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_remover.setForeground(new java.awt.Color(0, 153, 0));
        bt_remover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_remover.setLabel("Remover");
        bt_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerActionPerformed(evt);
            }
        });

        bt_pagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_pagamento.setForeground(new java.awt.Color(0, 153, 0));
        bt_pagamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_pagamento.setLabel("Pagamento");
        bt_pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pagamentoActionPerformed(evt);
            }
        });

        bt_imprimir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_imprimir.setForeground(new java.awt.Color(0, 153, 0));
        bt_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Untitled8.gif"))); // NOI18N
        bt_imprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_imprimir.setLabel("Imprimir");
        bt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_remover_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_quantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_pagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bt_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_remover_item, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nº do Pedido");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setDoubleBuffered(true);

        list_descricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_descricaoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(list_descricao);

        list_quantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_quantidadeMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(list_quantidade);

        list_preco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_precoMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(list_preco);

        list_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_totalMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(list_total);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Descrição");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Qnt.");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Preço");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Total");

        bt_novo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_novo.setForeground(new java.awt.Color(0, 153, 0));
        bt_novo.setText("Novo");
        bt_novo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Numerário");

        lbl_troco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_troco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_troco.setText("Troco");

        lbl_pedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_numerario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_numerario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_total, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addComponent(lbl_pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(lbl_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_numerario, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbl_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(173, 173, 173))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_remover_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_remover_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_remover_itemActionPerformed

    private void bt_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_quantidadeActionPerformed

    private void bt_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_removerActionPerformed

    private void bt_pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_pagamentoActionPerformed

    private void bt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_imprimirActionPerformed

    private void bt_cafeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cafeMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Café");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(0.8);
        list_preco.setModel(preco);
        
        total.addElement(0.8);
        list_total.setModel(total);
        
        total_pedido+=0.8;
        lbl_total.setText(Moeda.format(total_pedido));
        
    }//GEN-LAST:event_bt_cafeMouseReleased

    private void bt_capucinoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_capucinoMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Capucino");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(1.10);
        list_preco.setModel(preco);
        
        total.addElement(1.10);
        list_total.setModel(total);
        
        total_pedido+=1.10;
        lbl_total.setText(Moeda.format(total_pedido));
        
    }//GEN-LAST:event_bt_capucinoMouseReleased

    private void bt_cariocaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cariocaMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Carioca");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(0.9);
        list_preco.setModel(preco);
        
        total.addElement(0.9);
        list_total.setModel(total);
        
        total_pedido+=0.9;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_cariocaMouseReleased

    private void bt_galaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_galaoMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Galão");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(1.2);
        list_preco.setModel(preco);
        
        total.addElement(1.2);
        list_total.setModel(total);
        
        total_pedido+=1.2;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_galaoMouseReleased

    private void bt_garotoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_garotoMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Garoto");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(1);
        list_preco.setModel(preco);
        
        total.addElement(1);
        list_total.setModel(total);
        
        total_pedido+=1;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_garotoMouseReleased

    private void bt_descafeinadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_descafeinadoMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Descafeinado");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(0.9);
        list_preco.setModel(preco);
        
        total.addElement(0.9);
        list_total.setModel(total);
        
        total_pedido+=0.9;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_descafeinadoMouseReleased

    private void bt_mistaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mistaMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Mista");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(2);
        list_preco.setModel(preco);
        
        total.addElement(2);
        list_total.setModel(total);
        
        total_pedido+=2;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_mistaMouseReleased

    private void bt_salgadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_salgadoMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Salgado");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(1.5);
        list_preco.setModel(preco);
        
        total.addElement(1.5);
        list_total.setModel(total);
        
        total_pedido+=1.5;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_salgadoMouseReleased

    private void bt_boloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_boloMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Bolo");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(2.5);
        list_preco.setModel(preco);
        
        total.addElement(2.5);
        list_total.setModel(total);
        
        total_pedido+=2.5;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_boloMouseReleased

    private void bt_pizzaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_pizzaMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Pizza");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(2.5);
        list_preco.setModel(preco);
        
        total.addElement(2.5);
        list_total.setModel(total);
        
        total_pedido+=2.5;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_pizzaMouseReleased

    private void bt_folhadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_folhadoMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Folhado");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(2.3);
        list_preco.setModel(preco);
        
        total.addElement(2.3);
        list_total.setModel(total);
        
        total_pedido+=2.3;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_folhadoMouseReleased

    private void bt_sandesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sandesMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Sandes");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(2.5);
        list_preco.setModel(preco);
        
        total.addElement(2.5);
        list_total.setModel(total);
        
        total_pedido+=2.5;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_sandesMouseReleased

    private void bt_aguaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_aguaMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Água");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(0.8);
        list_preco.setModel(preco);
        
        total.addElement(0.8);
        list_total.setModel(total);
        
        total_pedido+=0.8;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_aguaMouseReleased

    private void bt_colaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colaMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Cola");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(1.2);
        list_preco.setModel(preco);
        
        total.addElement(1.2);
        list_total.setModel(total);
        
        total_pedido+=1.2;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_colaMouseReleased

    private void bt_sumoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sumoMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Sumo");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(1.5);
        list_preco.setModel(preco);
        
        total.addElement(1.5);
        list_total.setModel(total);
        
        total_pedido+=1.5;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_sumoMouseReleased

    private void bt_vinhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_vinhoMouseReleased
        // TODO add your handling code here:
        descricao.addElement("Vinho");
        list_descricao.setModel(descricao);
        
        quantidade.addElement(1);
        list_quantidade.setModel(quantidade);
        
        preco.addElement(3);
        list_preco.setModel(preco);
        
        total.addElement(3);
        list_total.setModel(total);
        
        total_pedido+=3;
        lbl_total.setText(Moeda.format(total_pedido));
    }//GEN-LAST:event_bt_vinhoMouseReleased

    private void list_descricaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_descricaoMouseReleased
        // TODO add your handling code here:
        list_quantidade.setSelectedIndex(list_descricao.getSelectedIndex());
        list_preco.setSelectedIndex(list_descricao.getSelectedIndex());
        list_total.setSelectedIndex(list_descricao.getSelectedIndex());
    }//GEN-LAST:event_list_descricaoMouseReleased

    private void list_quantidadeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_quantidadeMouseReleased
        // TODO add your handling code here:
        list_descricao.setSelectedIndex(list_quantidade.getSelectedIndex());
        list_preco.setSelectedIndex(list_quantidade.getSelectedIndex());
        list_total.setSelectedIndex(list_quantidade.getSelectedIndex());
    }//GEN-LAST:event_list_quantidadeMouseReleased

    private void list_precoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_precoMouseReleased
        // TODO add your handling code here:
        list_descricao.setSelectedIndex(list_preco.getSelectedIndex());
        list_quantidade.setSelectedIndex(list_preco.getSelectedIndex());
        list_total.setSelectedIndex(list_preco.getSelectedIndex());
    }//GEN-LAST:event_list_precoMouseReleased

    private void list_totalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_totalMouseReleased
        // TODO add your handling code here:
        list_descricao.setSelectedIndex(list_total.getSelectedIndex());
        list_quantidade.setSelectedIndex(list_total.getSelectedIndex());
        list_preco.setSelectedIndex(list_total.getSelectedIndex());
    }//GEN-LAST:event_list_totalMouseReleased

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        // TODO add your handling code here:
        Calendar C=new GregorianCalendar();
        int dia=C.get(Calendar.DAY_OF_MONTH);
        int mes=C.get(Calendar.MONTH);
        int ano=C.get(Calendar.YEAR);
        
        int hora=C.get(Calendar.HOUR_OF_DAY);
        int minuto=C.get(Calendar.MINUTE);
        int segundo=C.get(Calendar.SECOND);
        
        lbl_pedido.setText(Integer.toString(dia)+
                Integer.toString(mes)+
                Integer.toString(ano)+
                Integer.toString(hora)+
                Integer.toString(minuto)+
                Integer.toString(segundo));
    }//GEN-LAST:event_bt_novoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frl_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frl_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frl_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frl_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frl_pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionar;
    private javax.swing.JLabel bt_agua;
    private javax.swing.JLabel bt_bolo;
    private javax.swing.JLabel bt_cafe;
    private javax.swing.JLabel bt_capucino;
    private javax.swing.JLabel bt_carioca;
    private javax.swing.JLabel bt_cola;
    private javax.swing.JLabel bt_descafeinado;
    private javax.swing.JLabel bt_folhado;
    private javax.swing.JLabel bt_galao;
    private javax.swing.JLabel bt_garoto;
    private javax.swing.JButton bt_imprimir;
    private javax.swing.JLabel bt_mista;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_pagamento;
    private javax.swing.JLabel bt_pizza;
    private javax.swing.JButton bt_quantidade;
    private javax.swing.JButton bt_remover;
    private javax.swing.JButton bt_remover_item;
    private javax.swing.JLabel bt_salgado;
    private javax.swing.JLabel bt_sandes;
    private javax.swing.JLabel bt_sumo;
    private javax.swing.JLabel bt_vinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_numerario;
    private javax.swing.JLabel lbl_pedido;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_troco;
    private javax.swing.JList<String> list_descricao;
    private javax.swing.JList<String> list_preco;
    private javax.swing.JList<String> list_quantidade;
    private javax.swing.JList<String> list_total;
    // End of variables declaration//GEN-END:variables
}
