package pos;

import java.text.NumberFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.text.Position;


public class frm_pos extends javax.swing.JFrame {

    DefaultListModel descricao=new DefaultListModel();
    DefaultListModel quantidade=new DefaultListModel();
    DefaultListModel preco=new DefaultListModel();
    DefaultListModel total=new DefaultListModel();
    
    float total_pedido=0;
    
    NumberFormat Moeda=NumberFormat.getCurrencyInstance();
    
    public frm_pos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_cafe = new javax.swing.JLabel();
        bt_capucino = new javax.swing.JLabel();
        bt_descafeinado = new javax.swing.JLabel();
        bt_carioca = new javax.swing.JLabel();
        bt_galao = new javax.swing.JLabel();
        bt_garoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_mista = new javax.swing.JLabel();
        bt_salgado = new javax.swing.JLabel();
        bt_bolo = new javax.swing.JLabel();
        bt_pizza = new javax.swing.JLabel();
        bt_folhado = new javax.swing.JLabel();
        bt_sandes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bt_agua = new javax.swing.JLabel();
        bt_cola = new javax.swing.JLabel();
        bt_sumo = new javax.swing.JLabel();
        bt_vinho = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bt_adicionar = new javax.swing.JButton();
        bt_remover_item = new javax.swing.JButton();
        bt_quantidade = new javax.swing.JButton();
        bt_remover = new javax.swing.JButton();
        bt_pagamento = new javax.swing.JButton();
        bt_imprimir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lbl_pedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_descricao = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_qtd = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_preco = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_total = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        bt_novo = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_numerario = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbl_troco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cafetaria"));

        bt_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cafe.gif"))); // NOI18N
        bt_cafe.setText("Café");
        bt_cafe.setToolTipText("");
        bt_cafe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_cafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_cafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_cafeMouseReleased(evt);
            }
        });

        bt_capucino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_capucino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/capucino.gif"))); // NOI18N
        bt_capucino.setText("Capucino");
        bt_capucino.setToolTipText("");
        bt_capucino.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_capucino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_capucino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_capucino.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_descafeinado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_descafeinado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/descafeinado.gif"))); // NOI18N
        bt_descafeinado.setText("Descafeínado");
        bt_descafeinado.setToolTipText("");
        bt_descafeinado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_descafeinado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_descafeinado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_descafeinado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_carioca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_carioca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carioca.gif"))); // NOI18N
        bt_carioca.setText("Carioca");
        bt_carioca.setToolTipText("");
        bt_carioca.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_carioca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_carioca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_carioca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_galao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_galao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/galao.gif"))); // NOI18N
        bt_galao.setText("Galão");
        bt_galao.setToolTipText("");
        bt_galao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_galao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_galao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_galao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_garoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_garoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/garoto.gif"))); // NOI18N
        bt_garoto.setText("Garoto");
        bt_garoto.setToolTipText("");
        bt_garoto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_garoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_garoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_garoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_capucino, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_descafeinado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_carioca, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(bt_galao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(bt_garoto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_descafeinado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_garoto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_capucino, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_galao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_carioca, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pastelaria"));

        bt_mista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_mista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mista.gif"))); // NOI18N
        bt_mista.setText("Mista");
        bt_mista.setToolTipText("");
        bt_mista.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_mista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_mista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_mista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_salgado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_salgado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salgado.gif"))); // NOI18N
        bt_salgado.setText("Salgado");
        bt_salgado.setToolTipText("");
        bt_salgado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_salgado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_salgado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_salgado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_bolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_bolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_bolo.setText("Bolo");
        bt_bolo.setToolTipText("");
        bt_bolo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_bolo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_bolo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_bolo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_pizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_pizza.setText("Pizza");
        bt_pizza.setToolTipText("");
        bt_pizza.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_pizza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_pizza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_pizza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_folhado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_folhado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bolo.gif"))); // NOI18N
        bt_folhado.setText("Folhado");
        bt_folhado.setToolTipText("");
        bt_folhado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_folhado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_folhado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_folhado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_sandes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_sandes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mista.gif"))); // NOI18N
        bt_sandes.setText("Sandes");
        bt_sandes.setToolTipText("");
        bt_sandes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_sandes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_sandes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sandes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_mista, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_salgado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_bolo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(bt_folhado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(bt_sandes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_bolo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_sandes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_salgado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_folhado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_mista, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bebidas"));

        bt_agua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_agua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agua.gif"))); // NOI18N
        bt_agua.setText("Água");
        bt_agua.setToolTipText("");
        bt_agua.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_agua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_agua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_agua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_cola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cola.gif"))); // NOI18N
        bt_cola.setText("Cola");
        bt_cola.setToolTipText("");
        bt_cola.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_cola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_cola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_sumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_sumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sumo.gif"))); // NOI18N
        bt_sumo.setText("Sumo");
        bt_sumo.setToolTipText("");
        bt_sumo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_sumo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_sumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_vinho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_vinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vinho.gif"))); // NOI18N
        bt_vinho.setText("Vinho");
        bt_vinho.setToolTipText("");
        bt_vinho.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bt_vinho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_vinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_vinho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cola, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_sumo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_sumo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cola, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_agua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        bt_adicionar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_adicionar.setForeground(new java.awt.Color(0, 153, 102));
        bt_adicionar.setText("Adicionar item");
        bt_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_adicionarMouseReleased(evt);
            }
        });
        bt_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionarActionPerformed(evt);
            }
        });

        bt_remover_item.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_remover_item.setForeground(new java.awt.Color(0, 153, 102));
        bt_remover_item.setText("Remover item");

        bt_quantidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_quantidade.setForeground(new java.awt.Color(0, 153, 102));
        bt_quantidade.setText("Quantidade");

        bt_remover.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_remover.setForeground(new java.awt.Color(0, 153, 102));
        bt_remover.setText("Remover");

        bt_pagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_pagamento.setForeground(new java.awt.Color(0, 153, 102));
        bt_pagamento.setText("Pagamento");
        bt_pagamento.setToolTipText("");

        bt_imprimir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_imprimir.setForeground(new java.awt.Color(0, 153, 51));
        bt_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Untitled-8.gif"))); // NOI18N
        bt_imprimir.setText("Imprimir");
        bt_imprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(bt_pagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_quantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_remover_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bt_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_remover_item, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Nº de Pedido");
        jLabel17.setToolTipText("");

        lbl_pedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_pedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pedido.setToolTipText("");
        lbl_pedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        list_descricao.setToolTipText("");
        list_descricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_descricaoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(list_descricao);

        list_qtd.setToolTipText("");
        list_qtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_qtdMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(list_qtd);

        list_preco.setToolTipText("");
        list_preco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_precoMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(list_preco);

        list_total.setToolTipText("");
        list_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_totalMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(list_total);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Descrição");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Qtd.");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Preço");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Total");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addContainerGap())
        );

        bt_novo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_novo.setText("Novo");
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Total");

        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Numerário");
        jLabel27.setToolTipText("");

        lbl_numerario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Troco");
        jLabel29.setToolTipText("");

        lbl_troco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_numerario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_troco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(lbl_numerario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(lbl_troco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cafeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cafeMouseReleased
        AdicionarProduto("Café", 0.8f);
        
    }//GEN-LAST:event_bt_cafeMouseReleased

    private void list_descricaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_descricaoMouseReleased
        // TODO add your handling code here:
        list_qtd.setSelectedIndex(list_descricao.getSelectedIndex());
        list_preco.setSelectedIndex(list_descricao.getSelectedIndex());
        list_total.setSelectedIndex(list_descricao.getSelectedIndex());
    }//GEN-LAST:event_list_descricaoMouseReleased

    private void list_qtdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_qtdMouseReleased
        // TODO add your handling code here:
        list_descricao.setSelectedIndex(list_qtd.getSelectedIndex());
        list_preco.setSelectedIndex(list_qtd.getSelectedIndex());
        list_total.setSelectedIndex(list_qtd.getSelectedIndex());
    }//GEN-LAST:event_list_qtdMouseReleased

    private void list_precoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_precoMouseReleased
        // TODO add your handling code here:
        list_descricao.setSelectedIndex(list_preco.getSelectedIndex());
        list_qtd.setSelectedIndex(list_preco.getSelectedIndex());
        list_total.setSelectedIndex(list_preco.getSelectedIndex());
    }//GEN-LAST:event_list_precoMouseReleased

    private void list_totalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_totalMouseReleased
        // TODO add your handling code here:
        list_descricao.setSelectedIndex(list_total.getSelectedIndex());
        list_qtd.setSelectedIndex(list_total.getSelectedIndex());
        list_preco.setSelectedIndex(list_total.getSelectedIndex());
    }//GEN-LAST:event_list_totalMouseReleased

    private void AdicionarProduto(String NomeProduto,float PrecoProduto){
        try{
            int posicao=list_descricao.getNextMatch(NomeProduto,
                    0, Position.Bias.Forward);
            list_qtd.setSelectedIndex(posicao);
            int qtd=list_qtd.getSelectedValue()+1;
            quantidade.setElementAt(qtd, posicao);
           
            list_total.setSelectedIndex(posicao);
            total.setElementAt(qtd*PrecoProduto, posicao);
           
            total_pedido+=PrecoProduto;
            lbl_total.setText(Moeda.format(total_pedido));
            return;
        }
        catch(Exception e){  
        }
     
        // adicionar a descrição à lista
        descricao.addElement(NomeProduto);
        list_descricao.setModel(descricao);
       
        quantidade.addElement(1);
        list_qtd.setModel(quantidade);    
       
        preco.addElement(PrecoProduto);
        list_preco.setModel(preco);
       
        total.addElement(PrecoProduto);
        list_total.setModel(total);  
       
        total_pedido+=PrecoProduto;
        lbl_total.setText(Moeda.format(total_pedido));
    }
       
    
    
    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
        // TODO add your handling code here:
        Calendar C=new GregorianCalendar();
        int dia=C.get(Calendar.DAY_OF_MONTH);
        int mes=C.get(Calendar.MONTH);
        int ano=C.get(Calendar.YEAR);
        
        int hora=C.get(Calendar.HOUR_OF_DAY);
        int minuto=C.get(Calendar.MINUTE);
        int segundo=C.get(Calendar.SECOND);
        
        lbl_pedido.setText(Integer.toString(dia)+
                Integer.toString(mes)+
                Integer.toString(ano)+
                Integer.toString(hora)+
                Integer.toString(minuto)+
                Integer.toString(segundo));
        
    }//GEN-LAST:event_bt_novoActionPerformed

    private void bt_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_adicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_adicionarActionPerformed

    private void bt_adicionarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_adicionarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_adicionarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_adicionar;
    private javax.swing.JLabel bt_agua;
    private javax.swing.JLabel bt_bolo;
    private javax.swing.JLabel bt_cafe;
    private javax.swing.JLabel bt_capucino;
    private javax.swing.JLabel bt_carioca;
    private javax.swing.JLabel bt_cola;
    private javax.swing.JLabel bt_descafeinado;
    private javax.swing.JLabel bt_folhado;
    private javax.swing.JLabel bt_galao;
    private javax.swing.JLabel bt_garoto;
    private javax.swing.JButton bt_imprimir;
    private javax.swing.JLabel bt_mista;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_pagamento;
    private javax.swing.JLabel bt_pizza;
    private javax.swing.JButton bt_quantidade;
    private javax.swing.JButton bt_remover;
    private javax.swing.JButton bt_remover_item;
    private javax.swing.JLabel bt_salgado;
    private javax.swing.JLabel bt_sandes;
    private javax.swing.JLabel bt_sumo;
    private javax.swing.JLabel bt_vinho;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_numerario;
    private javax.swing.JLabel lbl_pedido;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_troco;
    private javax.swing.JList<String> list_descricao;
    private javax.swing.JList<String> list_preco;
    private javax.swing.JList<String> list_qtd;
    private javax.swing.JList<String> list_total;
    // End of variables declaration//GEN-END:variables
}
